# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='time',
            new_name='date',
        ),
    ]
